version: '3.2'

services:
  postgres:
    container_name: sponsorly_db
    image: postgres:12.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sponsorly_user
      - POSTGRES_PASSWORD=sponsorlydevelop
      - POSTGRES_DB=sponsorly_dev
      - PGDATA=/postgres/data
    volumes:
      - ./docker-data/postgres:/postgres
